global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  scrape_timeout:      10s # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
      
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
      
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'uptimerobot'
    scrape_interval: 5m
    scrape_timeout: 30s
    static_configs:
      - targets: ['uptimerobot-exporter:9429']
      
  - job_name: 'mediabox'
    static_configs:
      - targets:
        - 'mediabox-jellyfin:8096'
        - 'pihole-exporter:9707'
        - 'sonarr-exporter:9707'
        - 'radarr-exporter:9707'
#        - 'lidarr-exporter:9707'
        - 'deluge-exporter:9354'