global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  scrape_timeout:      10s # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
      
  - job_name: 'node'
    metrics_path: /node-exporter/metrics
    basic_auth:
      username: prometheus
      password: password
    static_configs:
      - targets: 
         - 'monitoring-servername.example.com'
         - 'monitoring-servername.example.com'
      
  - job_name: 'cadvisor'
    metrics_path: /cadvisor/metrics
    scrape_timeout: 15s
    basic_auth:
      username: prometheus
      password: password
    static_configs:
      - targets: 
        - 'monitoring-servername.example.com'
        - 'monitoring-servername.example.com'

  - job_name: 'traefik'
    static_configs:
      - targets: 
         - 'traefik-servername.example.com'
         - 'traefik-servername.example.com'

  - job_name: 'grafana'
    basic_auth:
      username: prometheus
      password: password
    static_configs:
      - targets: 
         - 'grafana:3000'

  - job_name: 'loki'
    basic_auth:
      username: prometheus
      password: password
    static_configs:
      - targets: 
         - 'loki:3100'

  - job_name: 'uptimerobot'
    scrape_interval: 5m
    scrape_timeout: 30s
    static_configs:
      - targets: 
         - 'uptimerobot-exporter:9707'
      
  # - job_name: 'pihole'
  #   static_configs:
  #     - targets:
  #       - 'pihole-exporter:9707'

  # - job_name: 'mediabox'
  #   static_configs:
  #     - targets:
  #       - 'jellyfin.example.com'
  #       - 'sonarr-exporter:9707'
  #       - 'radarr-exporter:9707'
  #       - 'lidarr-exporter:9707'
  #       - 'deluge.example.com'
  