version: "3.9"

services:
  uptimerobot-exporter:
    image: paolobasso/uptimerobot_exporter
    container_name: uptimerobot-exporter
    environment:
      - UPTIMEROBOT_READ_API_KEY=${UPTIMEROBOT_READ_API_KEY}
      - INTERVAL_SECONDS=300
      - LOG_LEVEL=INFO
      - PORT=9707
    restart: unless-stopped
    networks:
      - prometheus_network

#   pihole-exporter:
#     image: ekofr/pihole-exporter:latest
#     container_name: pihole-exporter
#     environment:
#       - PIHOLE_HOSTNAME=${PIHOLE_HOSTNAME}
#       - PIHOLE_PASSWORD=${PIHOLE_PASSWORD}
#       - INTERVAL=${PIHOLE_INTERVAL}
#       - PORT=9707
#     restart: unless-stopped
#     networks:
#       - prometheus_network

#   sonarr-exporter:
#     image: onedr0p/exportarr:master
#     container_name: sonarr-exporter
#     entrypoint: ["exportarr"]
#     command: ["sonarr"]
#     environment:
#       - URL=${SONARR_URL}
#       - APIKEY=${SONARR_APIKEY}
#       - ENABLE_EPISODE_QUALITY_METRICS=true
#       - PORT=9707
#     restart: unless-stopped
#     networks:
#       - prometheus_network

#   radarr-exporter:
#     image: onedr0p/exportarr:master
#     container_name: radarr-exporter
#     entrypoint: ["exportarr"]
#     command: ["radarr"]
#     environment:
#       - URL=${RADARR_URL}
#       - APIKEY=${RADARR_APIKEY}
#       - PORT=9707
#     restart: unless-stopped
#     networks:
#       - prometheus_network

#  lidarr-exporter:
#    image: onedr0p/exportarr:master
#    container_name: lidarr-exporter
#    entrypoint: ["exportarr"]
#    command: ["lidarr"]
#    environment:
#      - URL=${LIDARR_URL}
#      - APIKEY=${LIDARR_APIKEY}
#      - PORT=9707
#    restart: unless-stopped
#    networks:
#      - prometheus_network

networks:
  prometheus_network:
    external:
      name: ${PROMETHEUS_NETWORK}
